### ISSUE TITLE
Double vowels

### ISSUE THREAD

**Issue by rossjrw** [rossjrw/gallifreyo#7]
Double vowels can be represented by a double circle where the vowel's circle would normally be.

This could probably be another alphabet in the alphabet file:

```toml
[ShermanDoubleVowels]
priority = 2
letters = [
  { value = "AA", block = "vv", vert = -1, line = 0 },
  # ...
]
```
